version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pingbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      BOT_TOKEN:
      ADMIN_IDS:
      TELEGRAM_WEBAPP_URL: https://your-ngrok-id.ngrok-free.app/webapp
